def raise_exception():
    raise TypeError("Error")